- name: restart openvpn server
  service:
    name: openvpn@server
    state: restarted

- name: reload iptables
  service:
    name: iptables
    state: reloaded

- name: reload ip6tables
  service:
    name: ip6tables
    state: reloaded
