easyrsa_cmd: "/usr/share/easy-rsa/3/easyrsa"
easyrsa_dir: "/etc/easy-rsa"
openvpn_dev: "tun0"
openvpn_tls_key: "/etc/openvpn/myvpn.tlsauth"
openvpn_port: 8000
openvpn_cipher: "AES-128-GCM"
openvpn_ipv4_subnet: "10.8.0.0/24"
openvpn_proto: "udp"
