- name: "Install iptables-services"
  package:
    name: iptables-services
    state: present

- name: "/etc/sysconfig/iptables"
  template:
    src: iptables
    dest: /etc/sysconfig/iptables
  notify:
    - reload iptables

- name: "/etc/sysconfig/ip6tables"
  template:
    src: ip6tables
    dest: /etc/sysconfig/ip6tables
  notify:
    - reload ip6tables

- name: "Disable firewalld"
  service:
    name: firewalld
    enabled: false
    state: stopped
  ignore_errors: yes

- name: "Enable iptables service"
  service:
    name: iptables
    enabled: yes
    state: started

- name: "Enable ip6tables service"
  service:
    name: ip6tables
    enabled: yes
    state: started

- name: "sysctl net.ipv4.ip_forward=1"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_set: yes

- name: "sysctl net.ipv6.conf.all.forwarding=1"
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    state: present
    sysctl_set: yes
