- name: "EPEL repo"
  package:
    name: epel-release
    state: present

- name: "Install openvpn"
  package:
    name: openvpn
    state: present

- name: "Setup firewalld"
  import_tasks: firewalld.yml

- name: "Setup selinux"
  when: ansible_selinux and ansible_selinux.status == 'enabled'
  import_tasks: selinux.yml

- name: "{{ openvpn_tls_key }}"
  shell: "openvpn --genkey --secret {{ openvpn_tls_key }}"
  args:
    creates: "{{ openvpn_tls_key }}"
  notify:
    - restart openvpn server

- name: "/etc/openvpn/server.conf"
  template:
    src: server.conf
    dest: /etc/openvpn/server.conf
  notify:
    - restart openvpn server

- name: "start openvpn server"
  service:
    name: openvpn@server
    enabled: yes
    state: started

- name: "read {{ easyrsa_ca_crt }}"
  slurp:
    src: "{{ easyrsa_ca_crt }}"
  register: easyrsa_ca_crt_slurp

- name: "read {{ easyrsa_client_key }}"
  slurp:
    src: "{{ easyrsa_client_key }}"
  register: easyrsa_client_key_slurp

- name: "read {{ easyrsa_client_crt }}"
  slurp:
    src: "{{ easyrsa_client_crt }}"
  register: easyrsa_client_crt_slurp

- name: "read {{ openvpn_tls_key }}"
  slurp:
    src: "{{ openvpn_tls_key }}"
  register: openvpn_tls_key_slurp

- name: "{{ openvpn_client_config }}"
  template:
    src: client.ovpn
    dest: "{{ openvpn_client_config }}"

- name: "download {{ openvpn_client_config }}"
  fetch:
    src: "{{ openvpn_client_config }}"
    dest: "./downloads"
