- name: "EPEL repo"
  package:
    name: epel-release
    state: present

- name: "Install openvpn"
  package:
    name: openvpn
    state: present

- name: "Install easy-rsa"
  package:
    name: easy-rsa
    state: present

- name: "Install iptables-services"
  package:
    name: iptables-services
    state: present

- name: "sysctl net.ipv4.ip_forward=1"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_set: yes

- name: "/etc/sysconfig/iptables"
  template:
    src: iptables
    dest: /etc/sysconfig/iptables
  notify:
    - reload iptables

- name: "Enable iptables service"
  service:
    name: iptables
    enabled: yes
    state: started

- name: "sysctl net.ipv6.conf.all.forwarding=1"
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    state: present
    sysctl_set: yes

- name: "/etc/sysconfig/ip6tables"
  template:
    src: ip6tables
    dest: /etc/sysconfig/ip6tables
  notify:
    - reload ip6tables

- name: "Enable ip6gtables service"
  service:
    name: iptables
    enabled: yes
    state: started

- name: "{{ easyrsa_dir }}"
  file:
    path: "{{ easyrsa_dir }}"
    state: directory

- name: "easy-rsa init-pki"
  shell: "{{ easyrsa_cmd }} init-pki"
  args:
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_pki_dir }}"

- name: "easy-rsa build-ca"
  shell: "{{ easyrsa_cmd }} --batch build-ca nopass"
  args:
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_ca_crt }}"
  notify:
    - restart openvpn server

- name: "easy-rsa build-server-full"
  shell: "{{ easyrsa_cmd }} --batch build-server-full server nopass"
  args:
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_server_key }}"
  notify:
    - restart openvpn server

- name: "easy-rsa gen-dh"
  shell: "{{ easyrsa_cmd }} --batch gen-dh"
  args:
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_dh_pem }}"
  notify:
    - restart openvpn server

- name: "{{ openvpn_tls_key }}"
  shell: "openvpn --genkey --secret {{ openvpn_tls_key }}"
  args:
    creates: "{{ openvpn_tls_key }}"
  notify:
    - restart openvpn server

- name: "/etc/openvpn/server.conf"
  template:
    src: server.conf
    dest: /etc/openvpn/server.conf
  notify:
    - restart openvpn server

- name: "start openvpn server"
  service:
    name: openvpn@server
    enabled: yes
    state: started

- name: "easy-rsa build-client-full"
  shell: "{{ easyrsa_cmd }} --batch build-client-full client nopass"
  args:
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_client_key }}"

- name: "read {{ easyrsa_ca_crt }}"
  slurp:
    src: "{{ easyrsa_ca_crt }}"
  register: easyrsa_ca_crt_slurp

- name: "read {{ easyrsa_client_key }}"
  slurp:
    src: "{{ easyrsa_client_key }}"
  register: easyrsa_client_key_slurp

- name: "read {{ easyrsa_client_crt }}"
  slurp:
    src: "{{ easyrsa_client_crt }}"
  register: easyrsa_client_crt_slurp

- name: "read {{ openvpn_tls_key }}"
  slurp:
    src: "{{ openvpn_tls_key }}"
  register: openvpn_tls_key_slurp

- name: "{{ openvpn_client_config }}"
  template:
    src: client.ovpn
    dest: "{{ openvpn_client_config }}"

- name: "download {{ openvpn_client_config }}"
  fetch:
    src: "{{ openvpn_client_config }}"
    dest: "./downloads"
