- name: "fail2ban-server-{{ fail2ban_rpm_version }}.noarch.rpm"
  copy:
    src: "fail2ban-server-{{ fail2ban_rpm_version }}.noarch.rpm"
    dest: /tmp/

- name: fail2ban-server
  package:
    name: "/tmp/fail2ban-server-{{ fail2ban_rpm_version }}.noarch.rpm"
    state: present

- name: "fail2ban-systemd-{{ fail2ban_rpm_version }}.noarch.rpm"
  copy:
    src: "fail2ban-systemd-{{ fail2ban_rpm_version }}.noarch.rpm"
    dest: /tmp/

- name: fail2ban-systemd
  package:
    name: "/tmp/fail2ban-systemd-{{ fail2ban_rpm_version }}.noarch.rpm"
    state: present
  notify:
    - reload fail2ban

- name: /etc/fail2ban/jail.local
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
  notify:
    - reload fail2ban

- name: firewalld
  import_tasks: firewalld.yml

- name: start fail2ban on boot
  service:
    name: fail2ban
    enabled: yes
    state: started
